version: 0.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore

after_build:
  - ps: BuildScripts/CopyBinaries.ps1

configuration: Release

cache:
  - packages

artifacts:
  - path: bin/x86
    name: OBS GW2 Plugin v$(appveyor_build_version) (32-bit)
    type: zip
  - path: bin/x64
    name: OBS GW2 Plugin v$(appveyor_build_version) (64-bit)
    type: zip
