version: 0.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - nuget restore

configuration: Release

cache:
  - packages

artifacts:
  - path: Gw2Plugin\bin\$(configuration)
    name: OBS GW2 Plugin v$(appveyor_build_version)
    type: zip
